{{- if and .Values.celerDataCluster.enabledBe .Values.celerDataBeSpec .Values.celerDataBeSpec.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "celerdatacluster.be.configmap.name" . }}
  namespace: {{ template "celerdatacluster.namespace" . }}
  labels:
    cluster: {{ template "celerdatacluster.name" . }}
    app: "be"
data:
  {{- include "celerdatacluster.be.config" . | nindent 2 }}

{{- end }}

