apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "celerdatacluster.fe.configmap.name" . }}
  namespace: {{ template "celerdatacluster.namespace" . }}
  labels:
    cluster: {{ template "celerdatacluster.name" . }}
    app: "fe"
data:
  {{- include "celerdatacluster.fe.config" . | nindent 2 }}
