//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/api/autoscaling/v2beta2"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingPolicy) DeepCopyInto(out *AutoScalingPolicy) {
	*out = *in
	if in.HPAPolicy != nil {
		in, out := &in.HPAPolicy, &out.HPAPolicy
		*out = new(HPAPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingPolicy.
func (in *AutoScalingPolicy) DeepCopy() *AutoScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataBeSpec) DeepCopyInto(out *CelerDataBeSpec) {
	*out = *in
	in.CelerDataComponentSpec.DeepCopyInto(&out.CelerDataComponentSpec)
	if in.BeEnvVars != nil {
		in, out := &in.BeEnvVars, &out.BeEnvVars
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataBeSpec.
func (in *CelerDataBeSpec) DeepCopy() *CelerDataBeSpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataBeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataBeStatus) DeepCopyInto(out *CelerDataBeStatus) {
	*out = *in
	in.CelerDataComponentStatus.DeepCopyInto(&out.CelerDataComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataBeStatus.
func (in *CelerDataBeStatus) DeepCopy() *CelerDataBeStatus {
	if in == nil {
		return nil
	}
	out := new(CelerDataBeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataCluster) DeepCopyInto(out *CelerDataCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataCluster.
func (in *CelerDataCluster) DeepCopy() *CelerDataCluster {
	if in == nil {
		return nil
	}
	out := new(CelerDataCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelerDataCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataClusterList) DeepCopyInto(out *CelerDataClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CelerDataCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataClusterList.
func (in *CelerDataClusterList) DeepCopy() *CelerDataClusterList {
	if in == nil {
		return nil
	}
	out := new(CelerDataClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelerDataClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataClusterSpec) DeepCopyInto(out *CelerDataClusterSpec) {
	*out = *in
	if in.CelerDataFeSpec != nil {
		in, out := &in.CelerDataFeSpec, &out.CelerDataFeSpec
		*out = new(CelerDataFeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CelerDataBeSpec != nil {
		in, out := &in.CelerDataBeSpec, &out.CelerDataBeSpec
		*out = new(CelerDataBeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CelerDataCnSpec != nil {
		in, out := &in.CelerDataCnSpec, &out.CelerDataCnSpec
		*out = new(CelerDataCnSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CelerDataFeProxySpec != nil {
		in, out := &in.CelerDataFeProxySpec, &out.CelerDataFeProxySpec
		*out = new(CelerDataFeProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DisasterRecovery != nil {
		in, out := &in.DisasterRecovery, &out.DisasterRecovery
		*out = new(DisasterRecovery)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataClusterSpec.
func (in *CelerDataClusterSpec) DeepCopy() *CelerDataClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataClusterStatus) DeepCopyInto(out *CelerDataClusterStatus) {
	*out = *in
	if in.CelerDataFeStatus != nil {
		in, out := &in.CelerDataFeStatus, &out.CelerDataFeStatus
		*out = new(CelerDataFeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CelerDataBeStatus != nil {
		in, out := &in.CelerDataBeStatus, &out.CelerDataBeStatus
		*out = new(CelerDataBeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CelerDataCnStatus != nil {
		in, out := &in.CelerDataCnStatus, &out.CelerDataCnStatus
		*out = new(CelerDataCnStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CelerDataFeProxyStatus != nil {
		in, out := &in.CelerDataFeProxyStatus, &out.CelerDataFeProxyStatus
		*out = new(CelerDataFeProxyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DisasterRecoveryStatus != nil {
		in, out := &in.DisasterRecoveryStatus, &out.DisasterRecoveryStatus
		*out = new(DisasterRecoveryStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataClusterStatus.
func (in *CelerDataClusterStatus) DeepCopy() *CelerDataClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CelerDataClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataCnSpec) DeepCopyInto(out *CelerDataCnSpec) {
	*out = *in
	in.CelerDataComponentSpec.DeepCopyInto(&out.CelerDataComponentSpec)
	if in.CnEnvVars != nil {
		in, out := &in.CnEnvVars, &out.CnEnvVars
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoScalingPolicy != nil {
		in, out := &in.AutoScalingPolicy, &out.AutoScalingPolicy
		*out = new(AutoScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataCnSpec.
func (in *CelerDataCnSpec) DeepCopy() *CelerDataCnSpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataCnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataCnStatus) DeepCopyInto(out *CelerDataCnStatus) {
	*out = *in
	in.CelerDataComponentStatus.DeepCopyInto(&out.CelerDataComponentStatus)
	out.HorizontalScaler = in.HorizontalScaler
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataCnStatus.
func (in *CelerDataCnStatus) DeepCopy() *CelerDataCnStatus {
	if in == nil {
		return nil
	}
	out := new(CelerDataCnStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataComponentSpec) DeepCopyInto(out *CelerDataComponentSpec) {
	*out = *in
	in.CelerDataLoadSpec.DeepCopyInto(&out.CelerDataLoadSpec)
	if in.RunAsNonRoot != nil {
		in, out := &in.RunAsNonRoot, &out.RunAsNonRoot
		*out = new(bool)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(corev1.Capabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]ConfigMapReference, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretReference, len(*in))
		copy(*out, *in)
	}
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]corev1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(appsv1.StatefulSetUpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnlyRootFilesystem != nil {
		in, out := &in.ReadOnlyRootFilesystem, &out.ReadOnlyRootFilesystem
		*out = new(bool)
		**out = **in
	}
	if in.Sysctls != nil {
		in, out := &in.Sysctls, &out.Sysctls
		*out = make([]corev1.Sysctl, len(*in))
		copy(*out, *in)
	}
	if in.PersistentVolumeClaimRetentionPolicy != nil {
		in, out := &in.PersistentVolumeClaimRetentionPolicy, &out.PersistentVolumeClaimRetentionPolicy
		*out = new(appsv1.StatefulSetPersistentVolumeClaimRetentionPolicy)
		**out = **in
	}
	if in.MinReadySeconds != nil {
		in, out := &in.MinReadySeconds, &out.MinReadySeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataComponentSpec.
func (in *CelerDataComponentSpec) DeepCopy() *CelerDataComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataComponentStatus) DeepCopyInto(out *CelerDataComponentStatus) {
	*out = *in
	if in.FailedInstances != nil {
		in, out := &in.FailedInstances, &out.FailedInstances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreatingInstances != nil {
		in, out := &in.CreatingInstances, &out.CreatingInstances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunningInstances != nil {
		in, out := &in.RunningInstances, &out.RunningInstances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceNames != nil {
		in, out := &in.ResourceNames, &out.ResourceNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataComponentStatus.
func (in *CelerDataComponentStatus) DeepCopy() *CelerDataComponentStatus {
	if in == nil {
		return nil
	}
	out := new(CelerDataComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataFeProxySpec) DeepCopyInto(out *CelerDataFeProxySpec) {
	*out = *in
	in.CelerDataLoadSpec.DeepCopyInto(&out.CelerDataLoadSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataFeProxySpec.
func (in *CelerDataFeProxySpec) DeepCopy() *CelerDataFeProxySpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataFeProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataFeProxyStatus) DeepCopyInto(out *CelerDataFeProxyStatus) {
	*out = *in
	in.CelerDataComponentStatus.DeepCopyInto(&out.CelerDataComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataFeProxyStatus.
func (in *CelerDataFeProxyStatus) DeepCopy() *CelerDataFeProxyStatus {
	if in == nil {
		return nil
	}
	out := new(CelerDataFeProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataFeSpec) DeepCopyInto(out *CelerDataFeSpec) {
	*out = *in
	in.CelerDataComponentSpec.DeepCopyInto(&out.CelerDataComponentSpec)
	if in.FeEnvVars != nil {
		in, out := &in.FeEnvVars, &out.FeEnvVars
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataFeSpec.
func (in *CelerDataFeSpec) DeepCopy() *CelerDataFeSpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataFeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataFeStatus) DeepCopyInto(out *CelerDataFeStatus) {
	*out = *in
	in.CelerDataComponentStatus.DeepCopyInto(&out.CelerDataComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataFeStatus.
func (in *CelerDataFeStatus) DeepCopy() *CelerDataFeStatus {
	if in == nil {
		return nil
	}
	out := new(CelerDataFeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataLoadSpec) DeepCopyInto(out *CelerDataLoadSpec) {
	*out = *in
	in.ResourceRequirements.DeepCopyInto(&out.ResourceRequirements)
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(CelerDataService)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageVolumes != nil {
		in, out := &in.StorageVolumes, &out.StorageVolumes
		*out = make([]StorageVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ConfigMapInfo = in.ConfigMapInfo
	if in.StartupProbeFailureSeconds != nil {
		in, out := &in.StartupProbeFailureSeconds, &out.StartupProbeFailureSeconds
		*out = new(int32)
		**out = **in
	}
	if in.LivenessProbeFailureSeconds != nil {
		in, out := &in.LivenessProbeFailureSeconds, &out.LivenessProbeFailureSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ReadinessProbeFailureSeconds != nil {
		in, out := &in.ReadinessProbeFailureSeconds, &out.ReadinessProbeFailureSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(corev1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.ShareProcessNamespace != nil {
		in, out := &in.ShareProcessNamespace, &out.ShareProcessNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataLoadSpec.
func (in *CelerDataLoadSpec) DeepCopy() *CelerDataLoadSpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataLoadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataProbe) DeepCopyInto(out *CelerDataProbe) {
	*out = *in
	if in.InitialDelaySeconds != nil {
		in, out := &in.InitialDelaySeconds, &out.InitialDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataProbe.
func (in *CelerDataProbe) DeepCopy() *CelerDataProbe {
	if in == nil {
		return nil
	}
	out := new(CelerDataProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataService) DeepCopyInto(out *CelerDataService) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]CelerDataServicePort, len(*in))
		copy(*out, *in)
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataService.
func (in *CelerDataService) DeepCopy() *CelerDataService {
	if in == nil {
		return nil
	}
	out := new(CelerDataService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataServicePort) DeepCopyInto(out *CelerDataServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataServicePort.
func (in *CelerDataServicePort) DeepCopy() *CelerDataServicePort {
	if in == nil {
		return nil
	}
	out := new(CelerDataServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataWarehouse) DeepCopyInto(out *CelerDataWarehouse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataWarehouse.
func (in *CelerDataWarehouse) DeepCopy() *CelerDataWarehouse {
	if in == nil {
		return nil
	}
	out := new(CelerDataWarehouse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelerDataWarehouse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataWarehouseList) DeepCopyInto(out *CelerDataWarehouseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CelerDataWarehouse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataWarehouseList.
func (in *CelerDataWarehouseList) DeepCopy() *CelerDataWarehouseList {
	if in == nil {
		return nil
	}
	out := new(CelerDataWarehouseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelerDataWarehouseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataWarehouseSpec) DeepCopyInto(out *CelerDataWarehouseSpec) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(WarehouseComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataWarehouseSpec.
func (in *CelerDataWarehouseSpec) DeepCopy() *CelerDataWarehouseSpec {
	if in == nil {
		return nil
	}
	out := new(CelerDataWarehouseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerDataWarehouseStatus) DeepCopyInto(out *CelerDataWarehouseStatus) {
	*out = *in
	if in.WarehouseComponentStatus != nil {
		in, out := &in.WarehouseComponentStatus, &out.WarehouseComponentStatus
		*out = new(CelerDataCnStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerDataWarehouseStatus.
func (in *CelerDataWarehouseStatus) DeepCopy() *CelerDataWarehouseStatus {
	if in == nil {
		return nil
	}
	out := new(CelerDataWarehouseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapInfo) DeepCopyInto(out *ConfigMapInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapInfo.
func (in *ConfigMapInfo) DeepCopy() *ConfigMapInfo {
	if in == nil {
		return nil
	}
	out := new(ConfigMapInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapReference) DeepCopyInto(out *ConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapReference.
func (in *ConfigMapReference) DeepCopy() *ConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterRecovery) DeepCopyInto(out *DisasterRecovery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterRecovery.
func (in *DisasterRecovery) DeepCopy() *DisasterRecovery {
	if in == nil {
		return nil
	}
	out := new(DisasterRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterRecoveryStatus) DeepCopyInto(out *DisasterRecoveryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterRecoveryStatus.
func (in *DisasterRecoveryStatus) DeepCopy() *DisasterRecoveryStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterRecoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPAPolicy) DeepCopyInto(out *HPAPolicy) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2beta2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(v2beta2.HorizontalPodAutoscalerBehavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPAPolicy.
func (in *HPAPolicy) DeepCopy() *HPAPolicy {
	if in == nil {
		return nil
	}
	out := new(HPAPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalScaler) DeepCopyInto(out *HorizontalScaler) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalScaler.
func (in *HorizontalScaler) DeepCopy() *HorizontalScaler {
	if in == nil {
		return nil
	}
	out := new(HorizontalScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountInfo) DeepCopyInto(out *MountInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountInfo.
func (in *MountInfo) DeepCopy() *MountInfo {
	if in == nil {
		return nil
	}
	out := new(MountInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageVolume) DeepCopyInto(out *StorageVolume) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(corev1.HostPathVolumeSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageVolume.
func (in *StorageVolume) DeepCopy() *StorageVolume {
	if in == nil {
		return nil
	}
	out := new(StorageVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarehouseComponentSpec) DeepCopyInto(out *WarehouseComponentSpec) {
	*out = *in
	in.CelerDataComponentSpec.DeepCopyInto(&out.CelerDataComponentSpec)
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoScalingPolicy != nil {
		in, out := &in.AutoScalingPolicy, &out.AutoScalingPolicy
		*out = new(AutoScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarehouseComponentSpec.
func (in *WarehouseComponentSpec) DeepCopy() *WarehouseComponentSpec {
	if in == nil {
		return nil
	}
	out := new(WarehouseComponentSpec)
	in.DeepCopyInto(out)
	return out
}
