apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: kube-starrocks
  namespace: starrocks
  labels:
    cluster: kube-starrocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  starRocksFeSpec:
    image: "starrocks/fe-ubuntu:3.2-latest"
    replicas: 1
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 4
      memory: 4Gi
    service:
      type: ClusterIP
    annotations:
      app.starrocks.io/fe-config-hash: e615d940
    runAsNonRoot: false
    feEnvVars:
      - name: TZ
        value: Asia/Shanghai
    terminationGracePeriodSeconds: 120
    configMapInfo:
      configMapName: kube-starrocks-fe-cm
      resolveKey: fe.conf
  starRocksBeSpec:
    image: "starrocks/be-ubuntu:3.2-latest"
    replicas: 1
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 4
      memory: 4Gi
    service:
      type: ClusterIP
    annotations:
      app.starrocks.io/be-config-hash: 951886d3
    runAsNonRoot: false
    capabilities:
      add:
        - PERFMON
        - SYS_PTRACE
      drop:
        - SYS_ADMIN
    beEnvVars:
      - name: TZ
        value: Asia/Shanghai
    terminationGracePeriodSeconds: 120
    configMapInfo:
      configMapName: kube-starrocks-be-cm
      resolveKey: be.conf
