apiVersion: starrocks.com/v1alpha1
kind: StarRocksCluster
metadata:
  name: starrockscluster-sample
  namespace: starrocks
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:2.5.4
    replicas: 3
    requests:
      cpu: 4
      memory: 16Gi
  starRocksCnSpec:
    image: starrocks/cn-ubuntu:2.5.4
    replicas: 3
    requests:
      cpu: 4
      memory: 4Gi
  starRocksBeSpec:
    image: starrocks/be-ubuntu:2.5.4
    replicas: 3
    requests:
      cpu: 4
      memory: 8Gi
