apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: starrockscluster-sample
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:latest
    replicas: 3
    requests:
      cpu: 4
      memory: 16Gi
  starRocksCnSpec:
    image: starrocks/cn-ubuntu:latest
    replicas: 3
    requests:
      cpu: 4
      memory: 4Gi
