apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: starrockscluster-sample
  namespace: starrocks
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:latest
    replicas: 3
    requests:
      cpu: 4
      memory: 16Gi
  starRocksCnSpec:
    image: starrocks/cn-ubuntu:latest
    requests:
      cpu: 4
      memory: 4Gi
      #when you use autoscalingPolicy, it is recommended that replicas removed from manifests.
    autoScalingPolicy:
      # by default, starrocks autoscaler will create a HPA with v2beta2 version. you can specify the version here.
      version: v2beta2
      maxReplicas: 10
      minReplicas: 1
      hpaPolicy:
        metrics:
          - type: Resource
            resource:
              name: memory
              target:
                averageUtilization: 30
                type: Utilization
          - type: Resource
            resource:
              name: cpu
              target:
                averageUtilization: 30
                type: Utilization
        behavior:
          scaleUp:
            policies:
              - type: Pods
                value: 1
                periodSeconds: 10
          scaleDown:
            selectPolicy: Disabled
