# permissions for end users to edit celerdataclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: celerdatacluster-editor-role
rules:
- apiGroups:
  - celerdata.com
  resources:
  - celerdataclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - celerdata.com
  resources:
  - celerdataclusters/status
  verbs:
  - get
