# permissions for end users to view celerdataclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: celerdatacluster-viewer-role
rules:
- apiGroups:
  - celerdata.com
  resources:
  - celerdataclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - celerdata.com
  resources:
  - celerdataclusters/status
  verbs:
  - get
