{{- if and .Values.starrocksOperator.enabled .Values.global.rbac.create (eq .Values.global.rbac.serviceAccountName "") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template  "operator.serviceAccountName" . }}
  namespace: {{ template  "operator.namespace" . }}
{{- end }}
