{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
---
{{- end }}