apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: starrocks-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: starrocks-manager-role
subjects:
- kind: ServiceAccount
  name: starrocks-controller
  namespace: starrocks
