# permissions for end users to view starrocksclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starrockscluster-viewer-role
rules:
- apiGroups:
  - starrocks.com
  resources:
  - starrocksclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starrocks.com
  resources:
  - starrocksclusters/status
  verbs:
  - get
