apiVersion: starrocks.com/v1alpha1
kind: StarRocksCluster
metadata:
  name: starrockscluster-sample
spec:
  serviceAccount: starrocksAccount
  starRocksFeSpec:
    replicas: 3
    image: starrocks.com/fe:2.40
    storageVolumes:
      - name: fe-storage
        storageClassName: fe-storage
        mountPath: /data/fe/meta
    requests:
      cpu: 4
      mem: 16Gi
  starRocksBeSpec:
    replicas: 6
    image: starrocks.com/be:2.40
    storageVolumes:
      - name: be-storage
        storageClassName: be-storage
        mountPath: /data/be
    requests:
      cpu: 4
      mem: 16Gi
  StarRocksCnSpec:
    replicas: 3
    image: starrocks.com/cn:2.40
    requests:
      cpu: 4
      mem: 16Gi


