name: PR Labeler
on:
  pull_request_target:
    types: [opened]

permissions: write-all

jobs:
  pr-labeler:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
